INSERT INTO EMPLOYEE  (NAME,LAST_NAME) VALUES ('ramprakash','singh');
INSERT INTO EMPLOYEE  (NAME,LAST_NAME) VALUES ('ravindra','singh');
INSERT INTO EMPLOYEE  (NAME,LAST_NAME) VALUES ('amitendra','singh');

INSERT INTO ADDRESS  (STREET,EMP_ID) VALUES ('bangalore',1);
INSERT INTO ADDRESS  (STREET,EMP_ID) VALUES ('Palhanpur',1);
INSERT INTO ADDRESS  (STREET,EMP_ID) VALUES ('patna',2);