CREATE TABLE EMPLOYEE (
    EMP_ID  		INTEGER      	NOT NULL AUTO_INCREMENT,
    NAME 			VARCHAR(128) 	NOT NULL,
    LAST_NAME 		VARCHAR(128) 	NOT NULL,
    PRIMARY KEY (EMP_ID)
);

CREATE TABLE ADDRESS (
    ADDRESS_ID 	INT 			NOT NULL AUTO_INCREMENT,
    STREET 		VARCHAR(128) 	NOT NULL,
    EMP_ID 		INT,
    CONSTRAINT FK_EMPLOYEE_ADDRESS FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
    PRIMARY KEY (ADDRESS_ID)
);